export {default as Hero} from './Hero'
export {default as Mailchimp} from './Mailchimp'
export {default as TextSection} from './TextSection'
export {default as ImageSection} from './ImageSection'
export {default as Rectangles} from './Rectangles'
export {default as Rectangle} from './Rectangle'
export {default as Testimonial} from './Testimonial'
export {default as Testimonials} from './Testimonials'
